spring:
  profiles:
    # active: ${SPRING_PROFILE}
    # include: common, ${SPRING_PROFILE}
    active: production
    include: common, production
  devtools:
    add-properties: false
#    active: local
#    include: common, local